# Generated by Django 2.1.2 on 2018-11-13 18:53

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Root', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Computer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('computer_name', models.CharField(max_length=50)),
                ('start_date', models.DateTimeField(default=datetime.datetime.now)),
                ('update_date', models.DateTimeField(default=datetime.datetime.now)),
                ('last_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Root.Location')),
            ],
        ),
        migrations.CreateModel(
            name='ComputerNetworkSetting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateTimeField(default=datetime.datetime.now)),
                ('update_date', models.DateTimeField(default=datetime.datetime.now)),
                ('computer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ComputerManagement.Computer')),
                ('network_setting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Root.NetworkSetting')),
            ],
        ),
        migrations.CreateModel(
            name='ComputerSystemSetting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateTimeField(default=datetime.datetime.now)),
                ('update_date', models.DateTimeField(default=datetime.datetime.now)),
                ('computer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ComputerManagement.Computer')),
                ('system_setting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Root.SystemSetting')),
            ],
        ),
        migrations.AddField(
            model_name='computer',
            name='network_setting',
            field=models.ManyToManyField(through='ComputerManagement.ComputerNetworkSetting', to='Root.NetworkSetting'),
        ),
        migrations.AddField(
            model_name='computer',
            name='system_setting',
            field=models.ManyToManyField(through='ComputerManagement.ComputerSystemSetting', to='Root.SystemSetting'),
        ),
    ]
