# Generated by Django 2.1.2 on 2018-11-13 18:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('floor', models.SmallIntegerField(default=2)),
                ('start_date', models.DateTimeField(default=datetime.datetime.now)),
                ('update_date', models.DateTimeField(default=datetime.datetime.now)),
            ],
        ),
        migrations.CreateModel(
            name='NetworkSetting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_DHCP', models.BooleanField(default=True)),
                ('domain', models.CharField(max_length=20)),
                ('IPv4_addr1', models.PositiveSmallIntegerField(default=0)),
                ('IPv4_addr2', models.PositiveSmallIntegerField(default=0)),
                ('IPv4_addr3', models.PositiveSmallIntegerField(default=0)),
                ('IPv4_addr4', models.PositiveSmallIntegerField(default=0)),
                ('subnet_mask1', models.PositiveSmallIntegerField(default=255)),
                ('subnet_mask2', models.PositiveSmallIntegerField(default=255)),
                ('subnet_mask3', models.PositiveSmallIntegerField(default=255)),
                ('subnet_mask4', models.PositiveSmallIntegerField(default=0)),
                ('DNS_addr1', models.PositiveSmallIntegerField(default=0)),
                ('DNS_addr2', models.PositiveSmallIntegerField(default=0)),
                ('DNS_addr3', models.PositiveSmallIntegerField(default=0)),
                ('DNS_addr4', models.PositiveSmallIntegerField(default=0)),
                ('mac_address', models.CharField(max_length=50)),
                ('start_date', models.DateTimeField(default=datetime.datetime.now)),
                ('update_date', models.DateTimeField(default=datetime.datetime.now)),
            ],
        ),
        migrations.CreateModel(
            name='SystemSetting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('memory_mb', models.PositiveSmallIntegerField()),
                ('CPU_model', models.CharField(max_length=50)),
                ('manufacturer', models.CharField(max_length=50)),
                ('machine_model', models.CharField(max_length=50)),
                ('service_tag', models.CharField(max_length=50)),
                ('serial_num', models.CharField(max_length=50)),
                ('product_num', models.CharField(max_length=50)),
                ('warranty_expire_date', models.DateField()),
                ('start_date', models.DateTimeField(default=datetime.datetime.now)),
                ('update_date', models.DateTimeField(default=datetime.datetime.now)),
            ],
        ),
    ]
